package com.letscode.battleship.entity;

import java.util.Arrays;
import java.util.Random;

import static com.letscode.battleship.utils.GameScanner.enterShipNumber;

abstract class GameBoard {

    //The following chars are used to represent different elements in the battleship game.
    private char water = ' ';
    private char ship = 'N';
    private char hit = '*';
    private char miss = '-';

    //The following components define the size of the game board.
    private int gameBoardLength = 10;
    private int shipNumber = enterShipNumber();

    public char[][] gameBoard = generateGameBoard();

    public char[][] generateGameBoard() {
        char[][] gameBoard = new char[this.gameBoardLength][this.gameBoardLength];
        for (char[] row : gameBoard){
            Arrays.fill(row, this.water);
        }
        return placeShip(gameBoard, this.shipNumber, this.water, this.ship);
    }

    public char[][] placeShip(char[][] gameBoard, int shipNumber, char water, char ship) {
        int placedShips = 0;
        int gameBoardLength = gameBoard.length;
        while (placedShips < shipNumber) {

            //The location will be an array of integers generated by the method generateShipCoordinates().
            int[] shipLocation = generateCoordinates(gameBoardLength);

            char possibleShipPlacement = gameBoard[shipLocation[0]][shipLocation[1]];

            if (possibleShipPlacement == water) {
                gameBoard[shipLocation[0]][shipLocation[1]] = ship;
                placedShips++;
            }
        }
        return gameBoard;
    }

    //The method returns an array of int that wil be used to set the position of an element in the game board
    public int[] generateCoordinates(int gameBoardLength){
        int[] coordinates = new int[2];
        for (int i = 0; i< coordinates.length; i++){
            coordinates[i] = new Random().nextInt(gameBoardLength);
        }
        return coordinates;
    }

    //Getter methods to access private elements.
    public char getWater() {
        return water;
    }

    public char getShip() {
        return ship;
    }

    public char getHit() {
        return hit;
    }

    public char getMiss() {
        return miss;
    }

    public int getGameBoardLength() {
        return gameBoardLength;
    }

    public int getShipNumber() {
        return shipNumber;
    }

}
