package com.letscode.battleship.entity;

public class GameBoardPlayer extends GameBoard{

    public GameBoardPlayer() {
    }

    public char[][] updatePlayerBoard(char[][] gameBoard, int[] guessCoordinates, char locationViewUpdate) {
        int row = guessCoordinates[0];
        int col = guessCoordinates[1];
        gameBoard[row][col] = locationViewUpdate;
        return gameBoard;
    }

    public char evaluateComputerGuessAndGetTarget(int[] guessCoordinates, char[][] gameBoard, char ship, char water, char hit, char miss){
//        int placedShips = 0;
//        int gameBoardLength = gameBoard.length;
//        while (placedShips < shipNumber) {
//
//            //The location will be an array of integers generated by the method generateShipCoordinates().
//            int[] shipLocation = generateCoordinates(gameBoardLength);
//
//            char possibleShipPlacement = gameBoard[shipLocation[0]][shipLocation[1]];
//
//            if (possibleShipPlacement == water) {
//                gameBoard[shipLocation[0]][shipLocation[1]] = ship;
//                placedShips++;
//            }
//        }
//        return gameBoard;
//
//
//
//
//
//
//
        String message;
        int row =guessCoordinates[0];
        int col = guessCoordinates[1];
        char target = gameBoard[row][col];

        if (target == ship){
            message = "Computer hit your boat!";
            target = hit;
        } else if (target == water){
            message = "Computer hit the water!";
            target = miss;
        } else {
            message = "Computer was confused and repeated the shot!";
        }
        System.out.println(message);
        return target;
    }

//    @Override
//    public char[][] placeShip(char[][] gameBoard, int shipNumber, char water, char ship) {
//        int placedShips = 0;
//        int gameBoardLength = gameBoard.length;
//        int shipIdentification = 1;
//
//        while (placedShips < shipNumber) {
//
//            Printer.printGame("Your board", gameBoard, water, ship);
//            System.out.println("Where would you want to position the ship number " + shipIdentification + "?");
//            shipIdentification++;
//
//            int[] shipLocation = getUserCoordinates(gameBoardLength);
//
//            char playerShipPlacement = gameBoard[shipLocation[0]][shipLocation[1]];
//
//            if (playerShipPlacement == water) {
//                gameBoard[shipLocation[0]][shipLocation[1]] = ship;
//                placedShips++;
//            }
//        }
//        return gameBoard;
//    }
}
